---
# This playbook prints a simple debug message
- name: Echo
  hosts: localhost
  connection: local

  tasks:
  - name: Pause for 1 seconds
    pause:
      seconds: 1
  - name: Print debug message
    debug:
      msg: Hello, world!
  - name: Create a file called '/tmp/testfile.txt' with the content 'hello world'.
    copy:
      content: hello world
      dest: /tmp/testfile.txt
  - name: Pause for 1 seconds
    pause:
      seconds: 1
  - name: Execute the command in remote shell; stdout goes to the specified file on the remote
    ansible.builtin.shell: sleep 1
